---
# handlers file for ./ansible/roles/zabbix
- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted

- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: restart zabbix
  systemd:
    name: zabbix-server
    state: restarted
